services:
  prometheus:
    image: 'prom/prometheus'
    networks:
      - app_network
    ports:
      - '9090:9090'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - management.endpoints.web.exposure.include=*
      - management.endpoint.health.show.details=always
      - management.tracing.sampling.probability=1.0
    networks:
      - app_network
    depends_on:
      - prometheus
    ports:
      - '8080:8080'
networks:
  app_network:
    driver: bridge